In [ ]:

# numpy documentation
# https://numpy.org/doc/stable/index.html

INSTALLATION AND IMPORT

In [3]:
pip install numpy
# importing numpy library
import numpy as np

Note: you may need to restart the kernel to use updated packages.


Difference between list and array

In [9]:
#CREATING AN ARRAY  

x=np.array([1,2,3,4])
print(x)                                                                                                                        
    
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
#CREATING A LIST                            
  
Y=[1,2,3,4]             
print(Y)    

print(type(Y))           

[1, 2, 3, 4]
<class 'list'>


CREATING NumPy ARRAY

In [19]:
# CREATING ARRAYS FROM A LIST, COMMAND IS NP.ARRAY                                          
l=[1,2,3,4]
a=np.array(l)   
print(a)   
                                                                         
#TO FIND OUT IF ITS ARRAY OR NOT?   
#a       

#ANOTHER WAY TO FIND THE TYPE OF DATA IS:
print(type(a)) 

#another way without printing the out put:   
type(a) 

#to check the dimension of array:   
print(a.ndim)        

[1 2 3 4]
<class 'numpy.ndarray'>
1


CREATING DIFFERENT DIMENSIONS OF ARRAY and FIND ITS DIMENSION

In [14]:
# creating 0-D array
arr = np.array(42)
print(arr)                  

#checking dimensions
print(arr.ndim)

42
0


In [10]:
# creating 1-D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1) 

    #checking dimensions
print(arr1.ndim)

[1 2 3 4 5]


In [12]:
#creating 2-D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)                 

#checking dimensions
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]


In [17]:
#creating 3-D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)  

#checking dimensions
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [18]:
# creating higher dimensional arrays
arn = np.array([1, 2, 3, 4], ndmin=10)
print(arn)
print('number of dimensions :', arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
number of dimensions : 10


NUMPY DATA TYPE

In [5]:
# checking string data type integer    
var=[1,2,3,4]
var=np.array(var)   
print("Data type : ",var.dtype)  

Data type :  int32


In [9]:
# checking string data type float    
var = np.array([1.0,1.2,1.3])                                                                               
print("Data Type : ",var.dtype)

Data Type :  float64


In [7]:

# checking string data types
var = np.array(['apple', 'banana', 'cherry'])
print("Data type : ",var.dtype)    

Data type :  <U6


In [10]:
# checking string data types mix of string and integer  
var = np.array(['apple', 'banana', 'cherry', 1, 2, 5])
print("Data type : ",var.dtype)   

Data type :  <U11


HOW TO CHANGE DATA TYPE ?

In [15]:
X = np.array([1,2,3,4],dtype = np.int8 
print("data type : ",X.dtype) 


data type :  int8


In [26]:
x = np.array([1,2,3,4],dtype = 'U''f''O''S') 
print("Data Type : ",x.dtype)   
print(x)


Data Type :  <U1
['1' '2' '3' '4']


In [27]:
x = np.array([1,2,3,4],dtype = 'O') 
print("Data Type : ",x.dtype)   
print(x)

Data Type :  object
[1 2 3 4]


In [28]:
x3 = np.array([1,2,3,4])                                

x4 = x3.astype(float)   

print(x3)   
print(x4)

[1 2 3 4]
[1. 2. 3. 4.]


SHAPE

In [29]:
var = np.array([[1,2],[2,4]])   

print(var)  
print() # to print blank space
print(var.shape)

[[1 2]
 [2 4]]

(2, 2)


In [30]:
var = np.array([[1,2,3,4],[1,2,3,4]])   
print(var)  
print() # to print blank space
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


RESHAPE

In [51]:
var2 = np.array([1,2,3,4,5,6])   
print(var2)  
print() # to print blank space  
print("dimension : ",var2.ndim)
print("shape : ",var2.shape)    


x = var2.reshape(3,2)   
print(x)                                                
print("shape : ",x.shape)   
print("dimension : ",x.ndim)


[1 2 3 4 5 6]

dimension :  1
shape :  (6,)
[[1 2]
 [3 4]
 [5 6]]
shape :  (3, 2)
dimension :  2


PRCATICE QUESTION SHAPE ,RESHAPE

In [53]:
#create an multri dimentional array and find shape      
var1 = np.array([1,2,3,4], ndmin=3)#4)   
print(var1)  
print() # to print blank space      

print("dimension : ",var1.ndim) 

print("shape : ",var1.shape)        

print() # to print blank space          

#reshape
print(var1.reshape(2,2))

[[[1 2 3 4]]]

dimension :  3
shape :  (1, 1, 4)

[[1 2]
 [3 4]]


In [52]:
var2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   
print(var2)  
print("dimension : ",var2.ndim)
print("shape : ",var2.shape)    
print() # to print blank space   


x = var2.reshape(2,3,2)   
print(x)        
print("dimesnion : ",x.ndim)                                               
print("shape : ",x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
dimension :  1
shape :  (12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimesnion :  3
shape :  (2, 3, 2)


EXERCISE FOR PRACTICE



....................................................................................................................................................................................................................................................

In [29]:
# exercise fill the blank to create array
arr = np. array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [31]:
# fill with correct argument to create 2d array
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [32]:
# check the number of dimensions
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

1


In [ ]:
# exercise fill the blank to create array
arr = np.     ([1, 2, 3, 4, 5])
# fill with correct argument to create 2d array
arr = np.array([1, 2, 3, 4],    =2)
# check the number of dimensions
arr = np.array([1, 2, 3, 4])
print(arr.   )

SPECIAL TYPE OF ARRAYS

In [34]:
#creating array of zeros
a=np.zeros((2,3),dtype='int')
a

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
#creating array of 1's
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
#creating array with a single value
c=np.full((2,3),'abc')
c

array([['abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc']], dtype='<U3')

RANDOM

In [59]:
#generates ONE FLOAT VALUE ; THE RESULT WILL BE BW 0 TO 1
x = np.random.rand()
print(x)    

#generates 4 NUMBERS OF FLOAT VALUE ; THE RESULT WILL BE BW 0 TO 1  
y = np.random.rand(4)                                                                           

#generates random number that are positive and nehative both.
z=np.random.randn(4)
print(z)    

#ranf : close to 0 and less than 1
u=np.random.ranf(4)
print(u)   

0.6939903808548621
[-0.98832171 -0.35414972 -1.20538746 -1.34954004]
[0.53832412 0.51720651 0.62517021 0.09351525]


In [65]:
#creating using random integer values in given range EG. BQ 1 TO 10. 2D ARRAY WHICH HAS 2 ROWS AND 4 COLUMNS  
#d1=np.random.randint(min,max,total_values/array shape)  
d1=np.random.randint(1,10,5)
d2=np.random.randint(1,10,(2,4))
print(d1)

[6 2 1 7 5]


INDEXING NUMPY ARRAYS

In [70]:
# access first element
arr = np.array([1, 2, 3, 4])
print(arr[0])   

# to access second element
print(arr[1])   

# get 3rd and 4 th and add them
print(arr[2] + arr[-1])

1


In [73]:
#to aget number 8        
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr1) 
print(arr1.ndim)    
print() 

print(arr1[1,2])    

# to access 2?

print('2nd element on 1st row: ', arr[0, 1])    

#access element on the 2nd row and 5th column
print('5th element on 2nd row: ', arr[1, 4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2

8


In [79]:
    
# accessing 3-d (dimensions and index )
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
# accessing 3-d (dimensions and index )
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# access 3rd of second array of the first array "6"
#print(arr[0, 1, 2]) 

print(arr[1,0,1])

# print 11 using negative indexing
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#print(arr[-1,-1,-2] )

8


SLICING

In [ ]:
#array slicing
# slicing 1-d array [start:end] [start:end:step]
# slicing from index 1 to 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#slices from index 4 to the end
print(arr[4:])
# beginning to index 4
print(arr[:4])
# slicing from index 3 to index 1 from the end
print(arr[-3:-1])
# every other element from index 1 to index 5
print(arr[1:5:2])
# every other element from entire array
print(arr[::2])

In [93]:
# slicing 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) 
#arr
# From the second list, slice from index 1 to index 4 
print(arr[1, 1:4])
# from both return index 2
print(arr[0:2, 2])
# from both list slice 1 - 4(returns a 2 d array)
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [91]:
# From the second list/array, slice from index 1 to index 4 
print(arr[1, 1:4])

[7 8 9]


In [92]:
# from both return index 2
print(arr[0:2, 2])

[3 8]


ITERATE

In [97]:
# iterating(1-d)
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [98]:
# iterating 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [100]:
#iterating 3-d arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [101]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


jOINING

In [103]:
# joining arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [105]:
# joining rows
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


STACKING

In [ ]:
#stacking
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

In [109]:
#Horizontal Stacking, stacks one beside other
arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [110]:
#Vertical Stacking stacks one above other
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
#stacking along depth
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

SPLIT

In [113]:
# split arrays

arr = np.array([1, 2, 3, 4, 5, 6])
# splits in 3 parts
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [91]:
# Splitting 2-dimensional
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)    


# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))   



#Vertical Split
print("Splitting along Vertical axis into 2 parts:\n", np.vsplit(a, 2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Splitting along horizontal axis into 2 parts:
 [array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]
Splitting along Vertical axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


SEARCH

In [118]:
# search
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [119]:
# search even number
x = np.where(arr%2 == 0)
x

(array([1, 3, 5, 6], dtype=int64),)

In [120]:
# search odd number
x = np.where(arr%2 == 1)
x

(array([0, 2, 4], dtype=int64),)

SORT

In [121]:
# sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [122]:
# sorts alphabetically
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


SELF PRACTICE EXERCISE

In [ ]:
# exercise 2
#print first item in the array
arr = np.array([1, 2, 3, 4, 5])
print(arr  )
# print 50
arr = np.array([10, 20, 30, 40, 50])
print(arr   )
# print 50
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr  )
# print 11
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr )
#arr[1,0,1]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
# splits in 3 parts
newarr = np.array_split(arr, 4)

print(newarr)

In [ ]:
#exercise 4
# Use a correct NumPy method to join two arrays into a single array.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

In [ ]:
#exercise 3
#1.Everything from (including) the second item to 
#(not including) the fifth item.
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr   )
# 2.Everything from (including) the third item to 
#(not including) the fifth item

#3.Every other item from (including) the second item to 
#(not including) the fifth item.
#4.Every other item from the entire array.

In [ ]:
# iterating using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)